//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databasefirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int id { get; set; }
        public string vendor { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
